name: Order Service Build

on:
  push:
    paths:
      - 'order-service/**'
      - '.github/workflows/order-service-build.yml'
  pull_request:
    paths:
      - 'order-service/**'
      - '.github/workflows/order-service-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        id: setup-jdk-21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build Order Service
        env:
          JWT_SECRET: 6QeUA8IjhsI/dihQIkaJ8pzMHFKz0MrYLaPLtFydB7gfIaZHToh436RMVk4W40cRZelhfqbhLYOuAthqxvs+5w==
        run: |
          set -e
          export JAVA_HOME=${{ steps.setup-jdk-21.outputs.java-home }}
          export PATH=$JAVA_HOME/bin:$PATH
          echo "Content of application.properties before build:"
          cat order-service/src/main/resources/application.properties
          echo "--- End of application.properties ---"

          gradle --stop # Stop any existing Gradle daemons
          cd order-service
          ./gradlew clean build --no-daemon -Djwt.secret=${{ env.JWT_SECRET }}
